### ISSUE TITLE
TypeError: window.external.GetContext is not a function

### ISSUE THREAD

**Issue by Arthur-Z** [OfficeDev/Office-Add-in-Fabric-UI-Sample#2]
TypeError: window.external.GetContext is not a function
https://appsforoffice.microsoft.com/lib/1.1/hosted/o15apptofilemappingtable.js(line 11,col 117878)
my browser is Firefox 39.0
![qq 20151013134921](https://cloud.githubusercontent.com/assets/14676728/10597372/e0bf2174-7720-11e5-9ecd-cae2d6b2d936.jpg)

**Comment by LezaMax** [comment]
Sorry it took so long to get back to you. You need to run the sample inside an Office application as an add-in, otherwise it won't initialize properly. If you are looking for Fabric docs on generic web pages check http://dev.office.com/fabric.
