### ISSUE TITLE
ms-Panel-headerText looks terrible when line the wraps 

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/Office-Add-in-Fabric-UI-Sample#3]
The line height is pretty bad if the header text happens to wrap ![Bad line wrap](http://content.screencast.com/users/gavinbarron/folders/Snagit/media/facba89c-b948-43a8-bde6-8de8f8b4abec/02.04.2016-15.45.png)

**Comment by LezaMax** [comment]
Sorry it took so long to get back to you. Have you tried the latest version of Fabric? Is this still an issue for you? Thanks: https://dev.office.com/docs/add-ins/design/using-office-ui-fabric-js

**Comment by Rick-Kirkham** [comment]
This has been pending user response for over a week, so closing.
