### ISSUE TITLE
Please add some lines to "Try it Out section" on main page

### ISSUE THREAD

**Issue by solar4live** [OfficeDev/Office-Add-in-Fabric-UI-Sample#4]
I'm here just to know little bit about UI Fabric. This sample is exactly what I need. Thank you for create one. But please help me to try it:
1) what mean "npm install"? This is on my local computer? He just confirmed that he don't known this command. 
2) The same relate to "Run 'gulp serve-static' to run the node web server". Please give link to some resource to understand these pre-requisites.
3) Little bit more about "copy all the files in the Code Editor folder". Where this folder? 
Excuse me if all other readers understand these points. I'm just start to learn this technology.

**Comment by LezaMax** [comment]
Sorry it took so long to get back to you. Have you checked the instructions here, they are simpler and use the latest version of Fabric: https://dev.office.com/docs/add-ins/design/using-office-ui-fabric-js 

Please note the above is for using fabric in the context of Office Add-ins, if you are looking for documentation on fabric in general go to http://dev.office.com/fabric
