### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by pankajtakawale** [OfficeDev/Office-Add-in-Fabric-UI-Sample#5]
The Dropdown opens at the top-right corner of the taskpane. How can I make it open right below the dropdown text box. 

Environment: Mac Capitan, Office Word 2016 build number 15.23.2

![image](https://cloud.githubusercontent.com/assets/227570/16738906/b0d4ff72-4765-11e6-98dc-542fda71dbf9.png)

**Comment by LezaMax** [comment]
Sorry it took a while to follow up. Are you still experiencing this issue with the latest version of Fabric? https://dev.office.com/docs/add-ins/design/using-office-ui-fabric-js

**Comment by Rick-Kirkham** [comment]
This has been pending user response for over a week, so closing.
