### ISSUE TITLE
Couldn't setup this demo

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [OfficeDev/Office-Add-in-Fabric-UI-Sample#7]
Could you provide a solution file for Visual Studio? I had a lot of trouble trying make this work.

First, it cites "Get web application running", but later it says to copy all the files in a shared network folder.
Should I use the npm/gulp commands in the shared folder or it doesn't matter?

"Edit the element of the manifest file so that it points to the share location from step 1."
Well, I'm not sure which elements they are.

**Comment by lindalu-MSFT** [comment]
Hi, closing issue since this repo is no longer maintained.
